import { Book } from "./types";

export const CATEGORIES = [
  "Semua",
  "Garis Panduan Perancangan (GPP)",
  "Buletin",
  "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
  "Perancang Bandar",
  "Agama",
  "Sains",
  "Hobi",
  "Motivasi"
];

export const PPZU_BOOKS: Book[] = [
  {
    id: "PPZU-G01",
    title: "GPP Jilid 1: Garis Panduan Perancangan Perumahan (Edisi Ke-2)",
    author: "PLANMalaysia (Jabatan Perancangan Bandar dan Desa)",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-emerald-700 to-teal-900",
    description: "Manual standard perancangan perumahan kebangsaan. Menyediakan piawaian anjakan bangunan, kepadatan penduduk per ekar, kemudahan tempat letak kereta, dan spesifikasi kawasan lapang rekreasi dalam zon perumahan moden.",
    publishYear: 2024,
    pages: 145,
    chapters: [
      {
        id: "gpp-ch1",
        title: "Bab 1: Asas Piawaian Perumahan Negara",
        content: "Matlamat utama piawaian ini adalah untuk mewujudkan persekitaran kehidupan yang kondusif, selamat, dan sejahtera bagi seluruh rakyat Malaysia. Piawaian ini terpakai bagi semua projek perumahan baru sama ada oleh pemaju swasta mahupun agensi kerajaan. Aspek anjakan bangunan hadapan, belakang, dan tepi ditentukan untuk menjamin keselamatan sekiranya berlaku kebakaran dan pengudaraan yang sihat."
      },
      {
        id: "gpp-ch2",
        title: "Bab 2: Kepadatan dan Nisbah Plot",
        content: "Mengikut dasar perumahan mampu milik semasa, kepadatan dibenarkan sehingga 80 unit per ekar di kawasan korporat Transit Oriented Development (TOD). Nisbah plot minima dan zon penampan industri-perumahan mestilah sekurang-kurangnya 30 meter bagi industri ringan untuk memelihara kualiti hidup asnaf dan penduduk setempat."
      },
      {
        id: "gpp-ch3",
        title: "Bab 3: Rizab Kemudahan Lapang & Hijau",
        content: "Setiap pembangunan perumahan melebihi 10 ekar wajib memperuntukkan sekurang-kurangnya 10% daripada keluasan keseluruhan sebagai tapak kawasan lapang rekreasi, taman kejiranan, koridor hijau, dan kolam takungan banjir mesra alam."
      }
    ]
  },
  {
    id: "PPZU-G02",
    title: "GPP Jilid 2: Garis Panduan Perancangan Kawasan Lapang dan Rekreasi",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Rak G1 - Garis Panduan",
    coverColor: "from-teal-800 to-cyan-900",
    description: "Garis panduan komprehensif berkenaan pembangunan hijau bandar, hierarki taman rekreasi (daripada taman poket hingga ke taman bandar), penyediaan trek basikal, serta pengurusan landskap ekologi berdaya tahan.",
    publishYear: 2023,
    pages: 185,
    chapters: [
      {
        id: "gpp2-ch1",
        title: "Bab 1: Hierarki Taman Awam",
        content: "Penyusunan taman awam terbahagi kepada beberapa hierarki utama: Taman Poket (<0.5 ekar), Padang Permainan (0.5 hingga 1.5 ekar), Padang Kejiranan (1.5 hingga 5 ekar), dan Taman Tempatan (5 hingga 50 ekar). Kadar penyediaan standard adalah berdasarkan formula 2 hektar kawasan lapang bagi setiap 1,000 penduduk bandar."
      },
      {
        id: "gpp2-ch2",
        title: "Bab 2: Reka Bentuk Kemudahan Inklusif",
        content: "Kemudahan taman mestilah mesra orang kurang upaya (OKU) dengan tanjakan kerusi roda berpimpin, jubin sentuh (tactile paving) untuk golongan rabun/buta, serta pencahayaan mesra tenaga suria bagi tujuan keselamatan aktiviti rekreasi waktu malam."
      }
    ]
  },
  {
    id: "PPZU-G03",
    title: "GPP Jilid 3: Garis Panduan Pembangunan Fizikal Pantai Negara",
    author: "PLANMalaysia & JPS Malaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak G2 - Garis Panduan",
    coverColor: "from-sky-700 to-blue-900",
    description: "Siri panduan mitigasi bencana hakisan pantai, penetapan anjakan keselamatan laut minima bagi hotel, kemudahan awam, dan resort pelancongan di tepi pantai Semenanjung Malaysia, terutamanya bagi perairan Perak, Kedah, Perlis dan Pulau Pinang.",
    publishYear: 2022,
    pages: 120
  },
  {
    id: "PPZU-B01",
    title: "Buletin Perancangan PPZU: Pendigitalan GIS & Analisis Guna Tanah Pintar",
    author: "Lembaga Editor Pusat Sumber PPZU",
    category: "Buletin",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-indigo-800 to-purple-900",
    description: "Siri Buletin PPZU memaparkan liputan eksklusif mengenai aplikasi Sistem Maklumat Geografi (GIS) gred tinggi, penganalisisan data spatial di Kedah, Perak, Perlis, dan Pulau Pinang, serta integrasi pemodelan AI dalam simulasi koridor pengangkutan bandar pintar Utara.",
    publishYear: 2026,
    pages: 45,
    chapters: [
      {
        id: "bul1-ch1",
        title: "Bahagian 1: Pemetaan Spatial Automatik Zon Utara",
        content: "Pejabat Projek Zon Utara (PPZU) telah berjaya mengintegrasikan sistem pangkalan data spatial I-Plan ke dalam platform awan agensi. Sistem ini membolehkan analisis zon penampan alam sekitar (KSAS) dilakukan hampir serta-merta tanpa memerlukan audit fizikal yang panjang. Hal ini memudahkan kelulusan pembangunan industri berdaya tahan di kawasan pentadbiran utara semenanjung."
      },
      {
        id: "bul1-ch2",
        title: "Bahagian 2: Kajian Impak Kenaikan Paras Air Laut Utara",
        content: "Melalui dana penyelidikan spatial, pasukan GIS PPZU telah memetakan unjuran kenaikan aras laut di pesisiran pantai Kuala Kedah dan Kuala Perlis. Laporan awal mencadangkan pembinaan benteng eko-landskap dan zon penampan hutan bakau sejauh 100 meter bagi mengekang impak pasang surut maksimum berpaksikan perubahan iklim mutakhir."
      }
    ]
  },
  {
    id: "PPZU-B02",
    title: "Buletin Statistik Spatial & Guna Tanah Negeri-Negeri Zon Utara 2026",
    author: "Bahagian Kualiti & Pangkalan Data PPZU",
    category: "Buletin",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-blue-600 to-violet-800",
    description: "Buletin visual interaktif memaparkan perbandingan unjuran keluasan hutan simpan, kestabilan guna tanah pertanian, dan kadar rebakan bandar (urban sprawl) di Pulau Pinang, Kedah, Perlis, dan Perak.",
    publishYear: 2025,
    pages: 32,
    chapters: [
      {
        id: "bul2-ch1",
        title: "Halaman Utama: Ringkasan Prestasi Guna Tanah 2025",
        content: "Kawasan Zon Utara mencatatkan kenaikan perbandaran lestari sebanyak 8.5% hasil daripada pewartaan Rancangan Tempatan Daerah yang lebih agresif. Sektor eko-pelancongan hutan hujan tropika Perak dan kedah kekal terlindung, menyumbang kepada kestabilan indeks hijau penyerapan karbon sebanyak 1.2 tan metrik setahun bagi setiap hektar hutan warta."
      }
    ]
  },
  {
    id: "PPZU-B03",
    title: "Buletin Hijau: Inisiatif Reka Bentuk Bandar Pintar Rendah Karbon Utara",
    author: "Bahagian R&D Kakitangan PPZU",
    category: "Buletin",
    type: "Fizikal",
    status: "Dipinjam",
    location: "Rak B5 - Buletin Agensi",
    coverColor: "from-emerald-600 to-amber-700",
    description: "Risalah berkala mengenai sumbangan praktikal Pejabat Projek Zon Utara terhadap penggubalan garis panduan reka bentuk bandar mesra transit (TOD), pengurusan sisa pepejal mampan, dan penjimatan tenaga pintar pejabat cawangan utara.",
    publishYear: 2025,
    pages: 40
  },
  {
    id: "PPZU-L01",
    title: "Laporan Rancangan Fizikal Negara (RFN Ke-4)",
    author: "Majlis Perancangan Fizikal Negara",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-violet-700 to-pink-905",
    description: "Dokumen spatial tertinggi negara menggariskan strategi pembangunan koridor ekonomi utama Semenanjung Malaysia, pemuliharaan kawasan sensitif alam sekitar (KSAS), dan sistem rangkaian petempatan pusat-pusat bandar sehingga tahun 2040.",
    publishYear: 2024,
    pages: 350,
    chapters: [
      {
        id: "rfn-ch1",
        title: "Teras 1: Pertumbuhan Spatial Berdaya Tahan",
        content: "Laporan RFN Ke-4 menetapkan matlamat perbandaran padat bagi mengekang rebakan bandar yang tidak terkawal (urban sprawl). Semua projek perbandaran baru harus dirangka di sepanjang koridor pengangkutan transit berkelajuan tinggi. Ini penting untuk mengurangkan kadar pelepasan karbon negara sekurang-kurangnya 45% menjelang tahun 2030."
      },
      {
        id: "rfn-ch2",
        title: "Teras 2: Pemeliharaan Kawasan Sensitif Alam Sekitar (KSAS)",
        content: "KSAS Peringkat 1 (tiada pembangunan dibenarkan) merangkumi kawasan hutan simpan kekal melebihi 1,000 meter dari aras laut, habitat hidupan liar dilindungi, dan kawasan tadahan air minum. Manakala peringkat 2 membenarkan pelancongan ekologi terkawal tanpa melibatkan aktiviti pembalakan tegar."
      }
    ]
  },
  {
    id: "PPZU-L02",
    title: "Rancangan Struktur Negeri Perak 2040 (Warta)",
    author: "PLANMalaysia Negeri Perak",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Rak L1 - Laporan Struktur",
    coverColor: "from-orange-600 to-rose-900",
    description: "Warta rasmi pengisytiharan strategi spatial dan pembangunan fizikal negeri Perak Darul Ridzuan sehingga tahun 2040. Memperincikan koridor perindustrian Lembah Kinta, zon pelancongan marin Pangkor, dan pembangunan mampan sivil Taiping.",
    publishYear: 2024,
    pages: 280,
    chapters: [
      {
        id: "rsn-ch1",
        title: "Bab 1: Visi Perak Sejahtera 2030 Spatial",
        content: "Hala tuju utama RSN Perak 2040 adalah memacu perbandaran inklusif yang menyeimbangkan kesejahteraan luar bandar dan daya saing bandar metropolitan Ipoh. Pembangunan berasaskan ekonomi digital digalakkan dengan mengekalkan koridor agrikultur utama di Kerian, Kuala Kangsar, dan Hilir Perak sebagai jaminan sekuriti makanan negara."
      }
    ]
  },
  {
    id: "PPZU-L03",
    title: "Rancangan Tempatan Daerah Kubang Pasu 2035 (Warta)",
    author: "Majlis Perbandaran Kubang Pasu & PPZU PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak L2 - Laporan Tempatan",
    coverColor: "from-rose-600 to-indigo-950",
    description: "Pengezonan guna tanah berskala mikro daerah Kubang Pasu, Kedah Darul Aman. Menetapkankan kelas-kelas guna tanah, syarat ketinggian bangunan, pembangunan lebuh raya trans-nasional, dan zon sempadan Bukit Kayu Hitam.",
    publishYear: 2023,
    pages: 395,
    chapters: [
      {
        id: "rtdkp-ch1",
        title: "Perincian Zon Ekonomi Sempadan Khas (SBEZ)",
        content: "Seksyen ini memperincikan pembangunan fizikal Special Border Economic Zone (SBEZ) di Bukit Kayu Hitam yang dirangka bagi merangsang perdagangan dua hala Malaysia-Thailand, lengkap dengan hab logistik pintar bersepadu, pusat transit kastam moden, dan reka bentuk landskap industri mesra ekosistem."
      }
    ]
  },
  {
    id: "PPZU-L04",
    title: "Rancangan Kawasan Khas (RKK) Bandar Warisan Taiping",
    author: "Majlis Perbandaran Taiping & Pejabat Projek Zon Utara",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-amber-600 to-rose-950",
    description: "Pelan pembangunan terperinci bagi tujuan pemeliharaan bangunan warisan bersejarah kolonial, pelan pemuliharaan Taman Tasik Taiping, dan perancangan laluan pejalan kaki berkanopi di bandar tertua Perak.",
    publishYear: 2025,
    pages: 180,
    chapters: [
      {
        id: "rkk-ch1",
        title: "Perkara 1: Garis Panduan Fasad & Zon Teras Warisan",
        content: "Setiap premis komersial pra-perang di dalam zon teras warisan dilarang sama sekali mengubah suai struktur asal bangunan seperti tiang roman dan tingkap kayu berlipat. Cat warna bangunan mestilah menggunakan julat palet warna tanah (earth colors) bersesuaian dengan kelulusan khas jawatankuasa warisan MBDK."
      }
    ]
  },
  {
    id: "PPZU-L05",
    title: "Rancangan Struktur Negeri Kedah 2035",
    author: "PLANMalaysia Negeri Kedah",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Rujukan Sahaja",
    location: "Awan Digital PPZU",
    coverColor: "from-amber-700 to-emerald-900",
    description: "Dokumen rujukan strategik perancangan fizikal negeri Kedah Darul Aman. Mengintegrasikan unjuran pertumbuhan koridor logistik serantau, zon pelancongan mampan Kepulauan Langkawi, dan perlindungan dataran jelapang padi kebangsaan.",
    publishYear: 2023,
    pages: 250
  },
  {
    id: "PPZU-L06",
    title: "Rancangan Tempatan Daerah Kerian 2035",
    author: "Majlis Daerah Kerian & PPZU PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak L3 - Laporan Tempatan",
    coverColor: "from-cyan-800 to-slate-900",
    description: "Pelan guna tanah daerah Kerian, Perak. Menyediakan pelan pencegahan bencana banjir kawasan pertanian padi, strategi pengukuhan ekopelancongan Bukit Merah, dan pemetaan penempatan pinggir pantai Bagan Serai.",
    publishYear: 2024,
    pages: 310
  },
  {
    id: "PS-RE-0001",
    title: "Ringkasan Eksekutif Rancangan Wilayah Selatan Kedah, Pulau Pinang Utara Perak",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-blue-700 to-indigo-900",
    description: "Pelan rancangan perancangan menyeluruh bagi Wilayah Selatan Kedah, perbatasan Utara Perak, dan koridor Pulau Pinang demi keharmonian sosioekonomi fizikal.",
    publishYear: 2021,
    pages: 85
  },
  {
    id: "PS-RE-0002",
    title: "Ringkasan Eksekutif DRT Daerah Pendang",
    author: "PLANMalaysia Negeri Kedah",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak L2 - Laporan Tempatan",
    coverColor: "from-purple-700 to-amber-900",
    description: "Dokumen strategi ringkas perancangan lokal daerah Pendang, mengukuhkan perbandaran desa berasaskan sektor agrikultur bersepadu.",
    publishYear: 2022,
    pages: 64
  },
  {
    id: "PS-RE-0003",
    title: "Ringkasan Eksekutif Draf RKK Pantai Chenang",
    author: "PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-teal-700 to-emerald-950",
    description: "Laporan draf Rencana Kawasan Khas menyelaraskan koridor pelancongan Pantai Chenang, eko-marin, dan penyediaan anjakan keselamatan.",
    publishYear: 2021,
    pages: 42
  },
  {
    id: "PS-RE-0005",
    title: "Ringkasan Eksekutif Draff RKK Balik Pulau - Genting - Pulau Betong Pulau Pinang 2008-2020",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Fizikal",
    status: "Rujukan Sahaja",
    location: "Rak L4 - Rancangan Khas",
    coverColor: "from-emerald-700 to-lime-900",
    description: "Panduan pembangunan fizikal bersepadu bertemakan Eko Lancong dan Agro Lancong di kawasan luar bandar barat daya Pulau Pinang.",
    publishYear: 2020,
    pages: 58
  },
  {
    id: "PS-RE-0007",
    title: "Ringkasan Eksekutif DRT Daerah Kuala Muda 2020: Daerah Makmur, Bandaraya Dinamik & Mampan",
    author: "PLANMalaysia & Majlis Perbandaran Sungai Petani",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-indigo-700 to-violet-950",
    description: "Visi Daerah Kuala Muda mampan, menyusun atur kawasan perumahan padat, zon industri mampan, dan pelan hijau bandar raya dinamik.",
    publishYear: 2020,
    pages: 72
  },
  {
    id: "PS-RE-0013",
    title: "Ringkasan Eksekutif DRT Daerah Mersing 2018: Daerah Pelancongan Yang Unggul Dan Bertaraf Antarabangsa",
    author: "PLANMalaysia Negeri Johor",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-sky-700 to-blue-900",
    description: "Pelan strategik spatial pelancongan marin daerah Mersing, memulihara kepulauan eksotik, pulau taman laut, dan pesisir pantai mampan.",
    publishYear: 2018,
    pages: 94
  },
  {
    id: "PS-RE-0019-1",
    title: "Ringkasan Eksekutif Pelan Tindakan Pembangunan Warisan Jerai 'Geopark'",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Awan Digital & Rak L1",
    coverColor: "from-green-700 to-teal-950",
    description: "Pelan tindakan warisan bagi Jerai Geopark, menggariskan strategi perlindungan geologi, pendidikan komuniti, dan ekopelancongan geologi bernilai tinggi.",
    publishYear: 2021,
    pages: 110
  },
  {
    id: "PS-RE-0022",
    title: "Kajian Projek Penentuan Sempadan Bandar",
    author: "BRFN, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-slate-700 to-slate-900",
    description: "Kajian teknikal komprehensif bagi pelan rancangan penentuan perimeter, limitasi, dan kawalan gunatanah bersempadan fizikal.",
    publishYear: 2022,
    pages: 140
  },
  {
    id: "PS-RE-0026",
    title: "Laporan Ringkasan Eksekutif: Rancangan Fizikal Negara Keempat",
    author: "BRFN, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-rose-800 to-pink-950",
    description: "Rumusan tertinggi dasar guna tanah negara (RFN4) yang mensasarkan daya huni bandar, kelestarian fizikal, dan tadbir urus berdaya tahan.",
    publishYear: 2021,
    pages: 95
  },
  {
    id: "PS-RE-0028",
    title: "Ringkasan Eksekutif Draf Rancangan Tempatan Majlis Daerah Sik, Kedah 2035 (P)",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-green-600 to-emerald-900",
    description: "Ringkasan eksekutif draf rancangan tempatan yang berfokus kepada zon tadahan takbiran air dan memelihara pemajuan ekosistem mesra alam di Sik.",
    publishYear: 2023,
    pages: 78
  },
  {
    id: "PS-RE-0030",
    title: "Ringkasan Eksekutif Rancangan Kawasan Khas Pembangunan Wang Kelian, Perlis",
    author: "PLANMalaysia@Perlis",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Rak L4 & Awan Digital",
    coverColor: "from-yellow-700 to-amber-950",
    description: "Pelan pembangunan fizikal khas Wang Kelian sebagai zon pelancongan warisan perbatasan mampan bernilai ekologi tinggi.",
    publishYear: 2023,
    pages: 82
  },
  {
    id: "PS-RKK-0001",
    title: "Draf RKK Tanjung Dawai, Daerah Kuala Muda, Kedah",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-sky-700 to-blue-900",
    description: "Pelan rancangan pembangunan khusus pesisiran Kuala Muda Tanjung Dawai bagi menyeimbangkan penempatan nelayan dan industri rekreasi laut.",
    publishYear: 2021,
    pages: 165
  },
  {
    id: "PS-RKK-0002",
    title: "RKK Pantai Chenang, Langkawi (Warta)",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Rak L4 - Rancangan Khas",
    coverColor: "from-sky-600 to-indigo-900",
    description: "Dokumen berwarta panduan fasad pelancongan koridor Pantai Chenang, had bangunan tepi pantai, mengelungi visual alam semula jadi.",
    publishYear: 2013,
    pages: 210
  },
  {
    id: "PS-RKK-0003",
    title: "Laporan Draf RKK Kota Raja - Pauh Putra",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-orange-600 to-amber-900",
    description: "Penyusunan pelan tindakan fizikal integrasi bandar universiti bersepadu antara Kota Raja dengan Pauh Putra di Perlis.",
    publishYear: 2021,
    pages: 155
  },
  {
    id: "PS-RKK-0005-1",
    title: "Laporan Draf Awal RKK Kota Diraja Arau, Perlis",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak L4 - Rancangan Khas",
    coverColor: "from-yellow-600 to-orange-950",
    description: "Penyediaan reka bentuk bandar diraja berwarisan, memperindahkan laluan protokol kearah Istana Arau, landskap estetik, dan nodus pelancongan budaya.",
    publishYear: 2021,
    pages: 148
  },
  {
    id: "PS-RFN-0001",
    title: "Pelan Pembangunan Fizikal Koridor Raya Multimedia",
    author: "JPBD Semenanjung Malaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Fizikal",
    status: "Rujukan Sahaja",
    location: "Rak L1 - Laporan Struktur",
    coverColor: "from-blue-800 to-purple-950",
    description: "Pelan perancangan wilayah rujukan bersejarah yang melakarkan rangkaian petempatan industri teknologi tinggi koridor MSC.",
    publishYear: 2000,
    pages: 195
  },
  {
    id: "PS-RFN-0004",
    title: "Rancangan Fizikal Negara Ke Empat (RFN 4)",
    author: "PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-indigo-700 to-violet-900",
    description: "Pelan spatial tertinggi di peringkat kebangsaan, merangka rangkaian makro guna tanah, jaringan hijau ekologi mampan, dan zon risiko perubahan iklim.",
    publishYear: 2021,
    pages: 420
  },
  {
    id: "PS-RS-0003-1",
    title: "Rancangan Struktur Majlis Daerah Bandar Baharu 1990-2010",
    author: "Majlis Daerah Bandar Baharu",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Fizikal",
    status: "Rujukan Sahaja",
    location: "Rak L1 - Laporan Struktur",
    coverColor: "from-teal-600 to-indigo-900",
    description: "Strategi draf struktur bandar di perbatasan daerah bagi Bandar Baharu Kedah bagi menyeimbangkan zon guna tanah komersial.",
    publishYear: 1990,
    pages: 180
  },
  {
    id: "PS-RT-0084",
    title: "Rancangan Tempatan Majlis Daerah Pendang, Kedah 2035 (Penggantian) - Jilid 1",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Rak L2 & Awan Digital",
    coverColor: "from-emerald-700 to-green-950",
    description: "Pengezonan terperinci Jilid 1 merumus zon pertanian mampan, jaminan logistik pengangkutan komuter, dan kemantapan tadbir urus fizikal Pendang.",
    publishYear: 2025,
    pages: 320
  },
  {
    id: "PS-RT-0085",
    title: "Rancangan Tempatan Majlis Daerah Yan, Kedah 2035 (Penggantian) - Jilid 1",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-teal-800 to-sky-950",
    description: "Rancangan zon guna tanah daerah Yan, memperkukuh koridor warisan jerai geopark dan mengekalkan keindahan perbandaran ekopelancongan pesisir.",
    publishYear: 2025,
    pages: 280
  },
  {
    id: "PS-RT-0086",
    title: "Rancangan Tempatan Majlis Daerah Sik, Kedah 2035 (Penggantian) - Jilid 1",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Rak L2 - Laporan Tempatan",
    coverColor: "from-emerald-800 to-stone-900",
    description: "Pelan integriti kawasan tadahan, hutan simpan semulajadi daerah Sik, serta had perbandaran rendah karbon mesra alam.",
    publishYear: 2025,
    pages: 290
  },
  {
    id: "PS-RT-0087",
    title: "Rancangan Tempatan Majlis Daerah Padang Terap, Kedah 2035 (Penggantian) - Jilid 1",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-rose-800 to-slate-900",
    description: "Panduan zon and syarat guna tanah padang terap menyokong kewujudan hab pembuatan strategik Kedah Rubber City berdaya tinggi.",
    publishYear: 2025,
    pages: 310
  },
  // --- 1. Garis Panduan Perancangan (GPP) ---
  {
    id: "PS-GP-0001",
    title: "Garis Panduan Perancangan Bandar Selamat 2010",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-blue-600 to-cyan-900",
    description: "Menggariskan elemen teras pencegahan jenayah melalui reka bentuk persekitaran fizikal (CPTED) bagi merealisasikan komuniti mampan.",
    publishYear: 2010,
    pages: 120
  },
  {
    id: "PS-GP-0002",
    title: "Program Bandar Selamat Ilustrasi 23 Langkah Pencegahan Jenayah",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Awan Digital & Rak G1",
    coverColor: "from-cyan-700 to-blue-950",
    description: "Buku panduan bergambar komprehensif mengilustrasikan 23 tindakan pelaksanaan fizikal untuk meningkatkan darjah keselamatan awam.",
    publishYear: 2011,
    pages: 85
  },
  {
    id: "PS-GP-0009",
    title: "Garis Panduan Perancangan Bagi Pembangunan Small Office Home Office (SOHO) Negeri Selangor",
    author: "PLANMalaysia@Selangor",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-emerald-700 to-slate-900",
    description: "Standard perancangan fizikal bagi pemajuan ruang bekerja fleksibel SOHO dalam persekitaran perbandaran dinamik Selangor.",
    publishYear: 2016,
    pages: 95
  },
  {
    id: "PS-GP-0010",
    title: "Rekabentuk Bandar Selamat Panduan Pelaksanaan Pengasingan Laluan Pejalan Kaki",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak G2 - Garis Panduan",
    coverColor: "from-lime-700 to-teal-900",
    description: "Langkah-langkah teknikal melayakkan pejalan kaki diasingkan sepenuhnya daripada laluan bermotor dengan pemasangan bollard & pagar rel.",
    publishYear: 2012,
    pages: 110
  },
  {
    id: "PS-GP-0011",
    title: "Rekabentuk Bandar Selamat Garis Panduan Pemasangan CCTV Di Premis Perniagaan & Tempat Awam",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-sky-700 to-indigo-950",
    description: "Garis panduan standard konfigurasi lokasi, liputan, dan kriteria kualiti rakaman CCTV demi keselamatan pengguna premis komersial.",
    publishYear: 2012,
    pages: 60
  },
  {
    id: "PS-GP-0012",
    title: "Rekabentuk Bandar Selamat: Crime Prevention Through Environmental Design (CPTED) Implementation Guide",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-indigo-800 to-purple-950",
    description: "Panduan bernilai praktikal tinggi menceritakan pemetaan, pengawasan automatik, territoriality, serta kawalan akses fizikal.",
    publishYear: 2012,
    pages: 140
  },
  {
    id: "PS-GP-0024",
    title: "Garis Panduan Kejiranan Hijau",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-green-600 to-emerald-950",
    description: "Menggariskan elemen penting pembangunan kejiranan mesra alam: laluan basikal, penuaian air hujan, pengkomposan, dan reka bentuk landskap bertenaga rendah.",
    publishYear: 2015,
    pages: 130
  },
  {
    id: "PS-GP-0038",
    title: "Garis Panduan Pelaksanaan Healthy Walkable City",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-yellow-600 to-teal-900",
    description: "Strategi fizikal mewujudkan bandar boleh jalan kaki yang cergas, memperindah laluan kaki lima berkanopi dengan peneduh arbor semulajadi.",
    publishYear: 2018,
    pages: 90
  },
  {
    id: "PS-GP-0043",
    title: "Guidelines for Flood Risk Assessment and Flood Vulnerability Index for Critical Infrastructure in Malaysia",
    author: "CREAM & CIDB MALAYSIA",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak G3 - Garis Panduan Bencana",
    coverColor: "from-red-700 to-slate-900",
    description: "Panduan bertaraf kebangsaan membentangkan kerangka analisis risiko banjir besar bagi memelihara integriti lebuhraya, hospital & rantaian bekalan elektrik.",
    publishYear: 2020,
    pages: 180
  },
  {
    id: "PS-GP-0044",
    title: "Guidelines for Landslide Vulnerability Assessment and Development of Risk Index for Critical Infrastructure in Malaysia",
    author: "CREAM & CIDB MALAYSIA",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak G3 - Garis Panduan Bencana",
    coverColor: "from-amber-800 to-orange-950",
    description: "Metodologi penaksiran kekuatan tanah runtuh bagi kawasan berbukit batu kapur serta pembendungan risiko fizikal infrastruktur.",
    publishYear: 2020,
    pages: 160
  },
  {
    id: "PS-GP-0045",
    title: "Manual Garis Panduan & Piawaian Perancangan Negeri Selangor (Edisi Keempat)",
    author: "PLANMalaysia@Selangor",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Rak G1 & Awan Digital",
    coverColor: "from-rose-700 to-amber-900",
    description: "Kompilasi kriteria permohonan pemajuan guna tanah, anjakan, kepadatan kediaman maksimum, syarat kuota SOHO dan industri.",
    publishYear: 2022,
    pages: 240
  },
  {
    id: "PS-GP-0047-1",
    title: "Manual Rancangan Tempatan Edisi 2022",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-violet-700 to-pink-900",
    description: "Siri panduan seragam penyusunan warta rancangan perbandaran spatial daerah secara sistematik, bersepadu dan digital.",
    publishYear: 2022,
    pages: 125
  },
  {
    id: "PS-GP-0048",
    title: "Kompilasi Garis Panduan Perancangan Negeri Pulau Pinang 2022",
    author: "PLANMalaysia@Pulau Pinang",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-indigo-600 to-sky-900",
    description: "Himpunan enakmen perancangan fizikal khusus negeri Pulau Pinang, mengurus limitasi keterbinaan cerun tinggi dan pulau pulau warisan.",
    publishYear: 2022,
    pages: 310
  },
  {
    id: "PS-GP-0049",
    title: "Garis Panduan Perancangan Kemudahan Masyarakat",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak G1 - Garis Panduan",
    coverColor: "from-emerald-700 to-lime-900",
    description: "Menggariskan piawaian peletakan rizab dewan orang ramai, perpustakaan komuniti, had keluasan masjid, sekolah, dan kemudahan rekreasi sosial.",
    publishYear: 2022,
    pages: 105
  },
  {
    id: "PS-GP-0050",
    title: "Garis Panduan Perancangan Tempat Perkuburan Islam",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-stone-700 to-green-950",
    description: "Piawaian spatial penetapan arah kiblat pemakaman, zon penampan pokok teduh hiasan, jaminan logistik parking, dan jalan masuk berturap.",
    publishYear: 2023,
    pages: 75
  },
  {
    id: "PS-GP-0052",
    title: "Draf Panduan Mengarus Perdana Pelan Tindakan Iklim - Bandar Rendah Karbon Berdaya Tahan Perubahan Iklim Ke Dalam Rancangan Tempatan",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-emerald-800 to-teal-950",
    description: "Dokumen rujukan penting menggariskan strategi adaptasi fizikal perubahan iklim mikro bandar raya, mewajarkan pengurangan karbon spatial.",
    publishYear: 2024,
    pages: 150
  },
  {
    id: "PS-GP-0055",
    title: "Garis Panduan Perancangan Dan Pengurusan Kawasan Sensitif Alam Sekitar (PP KSAS)",
    author: "PLANMalaysia",
    category: "Garis Panduan Perancangan (GPP)",
    type: "Kedua-duanya",
    status: "Rujukan Sahaja",
    location: "Peti Khas KSAS & Awan Digital",
    coverColor: "from-green-800 to-emerald-950",
    description: "Peruntukan khusus mengenai larangan mutlak pembangunan fizikal di kawasan TADAHAN air gred 1 dan banjaran gunung kritikal.",
    publishYear: 2025,
    pages: 135
  },

  // --- 2. Pelan Tindakan Pembangunan ---
  {
    id: "PS-PTB-0001",
    title: "Laporan Akhir Pelan Tindakan Pembangunan Warisan Jerai 'Geopark'",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Rak L4 & Awan Digital",
    coverColor: "from-lime-600 to-emerald-950",
    description: "Dokumen komprehensif mengandungi pelan tindakan pengekalan khazanah geologi Jerai Geopark, menggerakkan pelancongan pendidikan tinggi.",
    publishYear: 2021,
    pages: 190
  },
  {
    id: "PS-PTB-0003-1",
    title: "Laporan Interim Pelan Induk Perancangan Fizikal Pelancongan Negeri Perlis",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-orange-600 to-red-900",
    description: "Rumusan awal kajian unjuran kedatangan pelancong dari perbatasan Padang Besar untuk pemetaan spatial eko-pelancongan Perlis.",
    publishYear: 2019,
    pages: 145
  },
  {
    id: "PS-PTB-0003-2",
    title: "Laporan Akhir Pelan Induk Perancangan Fizikal Pelancongan Negeri Perlis",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-red-600 to-rose-950",
    description: "Pelan tindakan mutakhir induk, zon reka bentuk tarikan fizikal, pembinaan resort mesra alam serta had muatan (carrying capacity) Wang Kelian.",
    publishYear: 2020,
    pages: 260
  },
  {
    id: "PS-PTB-0004",
    title: "Pelan Induk Kampung-Kampung Warisan Di Pulau Pinang: Pelan Pemeliharaan Pemuliharaan Pengurusan Kampung Warisan",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Awan Digital & Rak L4",
    coverColor: "from-amber-800 to-stone-900",
    description: "Menggariskan usaha menaik taraf, mengekalkan binaan kayu tradisional melayu kampung-kampung bersejarah terpilih di Seberang Perai.",
    publishYear: 2022,
    pages: 175
  },
  {
    id: "PS-PTB-0005",
    title: "Kajian Projek Penentuan Sempadan Bandar Negeri Kedah",
    author: "BRFN, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-slate-700 to-indigo-950",
    description: "Buku analisis spatial penyesuai sempadan pentadbiran majlis tempatan dengan sempadan fizikal geografi di Kedah.",
    publishYear: 2022,
    pages: 120
  },
  {
    id: "PS-PTB-0006-1",
    title: "Cadangan Pembinaan Dewan Serbaguna Terbuka (Open Shed) Majlis Perbandaran Kubang Pasu, Kedah Darul Aman",
    author: "Pejabat Projek Zon Utara, PLANMalaysia",
    category: "Laporan Perancangan (Rancangan Fizikal Negara, Rancangan Struktur Negeri, Rancangan Tempatan, Rancangan Kawasan Khas, Pelan Tindakan Khas)",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak L4 - Rancangan Khas",
    coverColor: "from-sky-700 to-slate-900",
    description: "Rekod teknikal cadangan pembinaan dewan mesra cuaca terbuka di dalam zon rekreasi kejiranan Kubang Pasu.",
    publishYear: 2023,
    pages: 98
  },

  // --- 3. Perancang Bandar (PB) ---
  {
    id: "PS-PB-0001",
    title: "Meeting Development Goals in Small Urban",
    author: "United Nationals Human Settlements Programme",
    category: "Perancang Bandar",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-blue-700 to-violet-950",
    description: "Laporan terperinci mengenai standard sivil, sanitasi dan matlamat keterbinaan bandar-bandar satelit berskala sederhana kecil.",
    publishYear: 2006,
    pages: 210
  },
  {
    id: "PS-PB-0002-1",
    title: "By Design - Urban Design in the Planning System",
    author: "Thomas Telford Publishing",
    category: "Perancang Bandar",
    type: "Fizikal",
    status: "Rujukan Sahaja",
    location: "Rak P1 - Perancang Bandar",
    coverColor: "from-neutral-700 to-zinc-900",
    description: "Panduan bernilai asas tinggi memaparkan anjakan, estetika fasad komersial dan interaksi visual pengguna dan bangunan.",
    publishYear: 2006,
    pages: 185
  },
  {
    id: "PS-PB-0004",
    title: "Designing the City",
    author: "Hilderbrand Frey",
    category: "Perancang Bandar",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-purple-800 to-slate-950",
    description: "Teori-teori perancangan morfologi bandar, jaminan pengudaraan mikro dan pencorakan koridor transit dinamik.",
    publishYear: 1999,
    pages: 145
  },
  {
    id: "PS-PB-0010",
    title: "Horikultur Hiasan & Landskap",
    author: "Mustafa Kamal Mohd",
    category: "Perancang Bandar",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Rak P1 & Awan Digital",
    coverColor: "from-green-700 to-emerald-950",
    description: "Buku rujukan tempatan pilihan mengenai pemilihan spesies tanaman teduhan bandar, reka bentuk tanah runtuh berkarakter landskap.",
    publishYear: 1995,
    pages: 220
  },
  {
    id: "PS-PB-0024",
    title: "Pengenalan Perancangan Wilayah",
    author: "John Glasson",
    category: "Perancang Bandar",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak P2 - Perancang Bandar",
    coverColor: "from-orange-700 to-amber-950",
    description: "Membincangkan makro-ekonomi wilayah spatial, rangkaian pengedaran logistik dan keharmonian dispariti luar bandar-bandar satelit.",
    publishYear: 1991,
    pages: 165
  },
  {
    id: "PS-PB-0033-1",
    title: "The Community Planning Handbook",
    author: "Nick Wates",
    category: "Perancang Bandar",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-indigo-650 to-emerald-900",
    description: "Langkah-langkah melibatkan partisipasi awam (public participation) dalam perancangan spatial komuniti, mengepit keadilan sosial.",
    publishYear: 2000,
    pages: 240
  },
  {
    id: "PS-PB-0090",
    title: "Laporan Maklumat Guna Tanah Negara",
    author: "PLANMalaysia",
    category: "Perancang Bandar",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-slate-700 to-slate-900",
    description: "Buku data kompilasi keluasan gunatanah semasa mengikut negeri dan daerah, penganalisisan data spatial I-Plan kebangsaan.",
    publishYear: 2021,
    pages: 180
  },
  {
    id: "PS-PB-0092",
    title: "Kuala Lumpur Climate Action Plan 2050",
    author: "Dewan Bandaraya Kuala Lumpur",
    category: "Perancang Bandar",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-emerald-700 to-indigo-950",
    description: "Pelan strategik spatial mitigasi krisis suhu bandar raya (Urban Heat Island), unjuran pengurangan tenaga elektrik fasa karbon maksima.",
    publishYear: 2021,
    pages: 110
  },

  // --- 4. Agama (AG) ---
  {
    id: "PS-AG-0001",
    title: "Al-Wafi Sharah Hadith 40 Imam Nawawi",
    author: "Dr. Mustafa Al-Buqha",
    category: "Agama",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak A1 - Agama",
    coverColor: "from-emerald-800 to-green-950",
    description: "Kitab huraian terperinci bagi himpunan 40 hadis asas fikh dan pembentukan sivil etika Islam berpaksikan Imam Nawawi.",
    publishYear: 2007,
    pages: 340
  },
  {
    id: "PS-AG-0002",
    title: "Sejarah 133 Wira Terbilang Di Zaman Rasulullah SAW",
    author: "Dr. Khalid Muhammad Khalid",
    category: "Agama",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak A1 - Agama",
    coverColor: "from-green-700 to-yellow-950",
    description: "Memaparkan sirah perjuangan pahlawan besar sekeliling baginda Nabi saw dalam mendirikan kedaulatan tamadun sivil Islam.",
    publishYear: 2007,
    pages: 280
  },
  {
    id: "PS-AG-0003",
    title: "Tafsir Al-Azhar Jilid 1",
    author: "Prof. Hamka",
    category: "Agama",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak A2 - Agama",
    coverColor: "from-emerald-900 to-stone-900",
    description: "Siri jilid 1 tafsiran Al-Quran agung nukisan karyawan Nusantara ulung Haji Abdul Malik Karim Amrullah (Hamka).",
    publishYear: 2003,
    pages: 410
  },
  {
    id: "PS-AG-0013",
    title: "Islamic Banking",
    author: "Kamal Khir",
    category: "Agama",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-blue-850 to-indigo-950",
    description: "Prinsip-prinsip syariah perbankan Islam: Murabahah, Takaful, pemetaan instrumen bebas daripada riba dan spekulasi tidak munasabah.",
    publishYear: 2008,
    pages: 220
  },
  {
    id: "PS-AG-0014",
    title: "Sirah & Riwayat Hidup Nabi Muhammad SAW",
    author: "Abu Mazaya Al-Hafiz",
    category: "Agama",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak A1 - Agama",
    coverColor: "from-emerald-700 to-teal-950",
    description: "Panduan sejarah hidup pesuruh Allah dari kelahiran, fasa menerima wahyu, pendirian piagam Madinah sehingga kewafatan.",
    publishYear: 2006,
    pages: 310
  },
  {
    id: "PS-AG-0015",
    title: "Ada Apa Dengan Islam",
    author: "Dato' Dr Haron Din",
    category: "Agama",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Awan Digital & Rak A3",
    coverColor: "from-green-600 to-emerald-900",
    description: "Buku penjelasan mendasar menceritakan rukun iman, faham akidah yang lurus dan keindahan cara hidup muslim.",
    publishYear: 2007,
    pages: 180
  },
  {
    id: "PS-AG-0016",
    title: "Keadilan Membebas Manusia",
    author: "Dato' Dr Haron Din",
    category: "Agama",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak A3 - Agama",
    coverColor: "from-green-800 to-indigo-950",
    description: "Ulasan syiar syariah menyangkut sistem persaudaraan hak asasi, had batasan kebebasan sivil dan maruah insaniah.",
    publishYear: 2007,
    pages: 215
  },
  {
    id: "PS-AG-0022",
    title: "Isu Pembangunan Tanah Wakaf",
    author: "Kamarudin Ngah",
    category: "Agama",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak A3 - Agama",
    coverColor: "from-teal-800 to-stone-900",
    description: "Kajian analisis pengurusan spatial tanah wakaf yang terbiar, membincangkan undang-undang tadbir urus fizikal tanah di Malaysia.",
    publishYear: 1992,
    pages: 150
  },
  {
    id: "PS-AG-0024",
    title: "Wasiat Imam Ghazali",
    author: "Imam Al-Ghazali",
    category: "Agama",
    type: "Fizikal",
    status: "Rujukan Sahaja",
    location: "Rak A1 - Khas Klasik",
    coverColor: "from-emerald-950 to-black",
    description: "Nasihat mendalam mengenai pembersihan rohani (Tasawuf), adab bermasyarakat dan penyucian niat demi keredhaan ilahi.",
    publishYear: 2004,
    pages: 135
  },

  // --- 5. Sains (SS) ---
  {
    id: "PS-SS-0001-1",
    title: "The Environment",
    author: "Prof. Dato' Dr. Sham Sani",
    category: "Sains",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-amber-700 to-emerald-950",
    description: "Buku rujukan unggul membentangkan ekologi penstrukturan kepulauan cuaca, impak rebakan penempatan sivil dan pengurusan pencemaran.",
    publishYear: 1998,
    pages: 160
  },
  {
    id: "PS-SS-0002",
    title: "Plants",
    author: "Prof. Dato' Dr. Sham Sani",
    category: "Sains",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-green-600 to-teal-900",
    description: "Analisis botani flora hutan hujan tropika Malaysia, siri penyerapan karbon, dan jaminan eko-biodiversiti hutan warta.",
    publishYear: 1998,
    pages: 140
  },
  {
    id: "PS-SS-0006",
    title: "Wild Malaysia",
    author: "Junaidi Payne",
    category: "Sains",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak S1 - Sains",
    coverColor: "from-lime-800 to-emerald-950",
    description: "Memaparkan fotografi hidupan liar eksotik hutan hujan Borneo dan Semenanjung, membentangkan inisiatif tumpuan ekorimba.",
    publishYear: 1999,
    pages: 210
  },
  {
    id: "PS-SS-0008",
    title: "The Polycentric Metropolis",
    author: "Peter Hall & Kathy Pain",
    category: "Sains",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-sky-800 to-indigo-950",
    description: "Sains sosial spatial mengkaji corak megacity bersepadu, perpindahan populasi komuter harian dan jaringan lebuhraya.",
    publishYear: 2006,
    pages: 290
  },
  {
    id: "PS-SS-0012-1",
    title: "Melaka City Image",
    author: "JPBD Semenanjung Malaysia",
    category: "Sains",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak S2 - Kajian Bandar",
    coverColor: "from-red-700 to-red-950",
    description: "Buku pemetaan spatial perancangan zon warisan UNESCO Melaka, fasad rumah kedai klasik dan nodus visual sejarah utama.",
    publishYear: 2003,
    pages: 130
  },
  {
    id: "PS-SS-0018-1",
    title: "The New Urbanism",
    author: "Peter Katz",
    category: "Sains",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-indigo-700 to-sky-950",
    description: "Paradigma reka bentuk bandar mesra pejalan kaki, mewujudkan bento grid kedai, rumah dan pejabat di lokasi zon setempat.",
    publishYear: 1994,
    pages: 250
  },
  {
    id: "PS-SS-0031-1",
    title: "Pearl of Perlis",
    author: "Kasim Osman & Rahimatsoh Amat",
    category: "Sains",
    type: "Kedua-duanya",
    status: "Tersedia",
    location: "Rak S1 & Awan Digital",
    coverColor: "from-yellow-600 to-emerald-950",
    description: "Memaparkan keindahan geologi batu kapur Perlis, biodiversiti flora khas, herba langka, dan eko-sistem geo-pelancongan perbatasan.",
    publishYear: 2002,
    pages: 145
  },

  // --- 6. Hobi (HB) ---
  {
    id: "PS-HB-0001",
    title: "Tropical Living",
    author: "Elizabeth V. Reyes",
    category: "Hobi",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak H1 - Hobi",
    coverColor: "from-amber-600 to-orange-900",
    description: "Inspirasi reka bentuk dalaman bertemakan tropika moden, menyusun atur pengaliran angin semula jadi dan landskap pokok keladi hiasan.",
    publishYear: 2000,
    pages: 180
  },
  {
    id: "PS-HB-0003",
    title: "Art School: How to Paint & Draw",
    author: "Hazel Harrison",
    category: "Hobi",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak H1 - Hobi",
    coverColor: "from-rose-600 to-indigo-900",
    description: "Panduan lengkap teknik melukis cat minyak, arkilik, lakaran struktur fizikal monumen dengan perspektif tumpu.",
    publishYear: 2007,
    pages: 240
  },
  {
    id: "PS-HB-0006",
    title: "Modern Tropical Garden Design",
    author: "Made Vijaya",
    category: "Hobi",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak H2 - Landskap",
    coverColor: "from-green-600 to-teal-950",
    description: "Mengilustrasikan reka bentuk taman air balinesia, kolam batu alam semula jadi, pokok daun lebar berdinding batu bata lembut.",
    publishYear: 2007,
    pages: 190
  },
  {
    id: "PS-HB-0015",
    title: "Cita Rasa Selera Nyonya, India, Thailand dan Timur Tengah",
    author: "Zarina Abd. Aziz",
    category: "Hobi",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak H1 - Hobi",
    coverColor: "from-rose-700 to-amber-950",
    description: "Himpunan resipi masakan warisan pelbagai etnik, kaya dengan adunan rempah ratus semulajadi menyelerakan.",
    publishYear: 2007,
    pages: 160
  },
  {
    id: "PS-HB-0023",
    title: "Auto Repair for Dummies",
    author: "Deanna Sclar",
    category: "Hobi",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-stone-600 to-slate-900",
    description: "Panduan langkah-demi-langkah penjagaan enjin kenderaan bermotor ringan, mengenal pasti kotak fius, mengganti minyak pelincir.",
    publishYear: 1999,
    pages: 320
  },
  {
    id: "PS-HB-0033",
    title: "The Kampung Boy",
    author: "LAT",
    category: "Hobi",
    type: "Fizikal",
    status: "Rujukan Sahaja",
    location: "Rak H3 - Khas Klasik",
    coverColor: "from-yellow-700 to-stone-900",
    description: "Karya kartun komik autobiografi tersohor Datuk Lat, memaparkan nostalgic kehidupan sivil dan landskap luar bandar era lampau.",
    publishYear: 2007,
    pages: 148
  },

  // --- 7. Motivasi (MT) ---
  {
    id: "PS-MT-0001",
    title: "Working Smart",
    author: "Schulman & Kowadlo",
    category: "Motivasi",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak M1 - Motivasi",
    coverColor: "from-indigo-600 to-sky-900",
    description: "Teknik memaksimumkan produktiviti bertindak, menumpukan delegasi, pengurusan kalendar kerja pejabat tanpa stress.",
    publishYear: 2005,
    pages: 210
  },
  {
    id: "PS-MT-0005-1",
    title: "The 8th Habit",
    author: "Stephen R. Covey",
    category: "Motivasi",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-blue-750 to-indigo-950",
    description: "Garis penting kepimpinan fasa baharu, memacu keberkesanan kendiri ke darjah kecemerlangan holistik organisasi.",
    publishYear: 2004,
    pages: 380
  },
  {
    id: "PS-MT-0007",
    title: "Strategy Maps",
    author: "Robert S. Kaplan",
    category: "Motivasi",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-indigo-800 to-slate-950",
    description: "Sistem pengurusan bersandarkan Balanced Scorecard, menterjemahkan matlamat visi ke pemetaan strategik fizikal.",
    publishYear: 2004,
    pages: 320
  },
  {
    id: "PS-MT-0030",
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    category: "Motivasi",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak M1 - Motivasi",
    coverColor: "from-cyan-700 to-blue-900",
    description: "Buku rujukan agung kepimpinan diri, membentangkan sinergi, bersikap proaktif, dan prinsip menang-menang (Win-Win).",
    publishYear: 2006,
    pages: 340
  },
  {
    id: "PS-MT-0031",
    title: "The Ultimate Book of Mind Maps",
    author: "Tony Buzan",
    category: "Motivasi",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-violet-600 to-purple-950",
    description: "Sains berfikir mampan, penganalisisan bercabang, mengorganisasikan visual idea komplex secara rajah berstruktur.",
    publishYear: 2000,
    pages: 175
  },
  {
    id: "PS-MT-0068",
    title: "Awaken The Giant Within",
    author: "Anthony Robbins",
    category: "Motivasi",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak M2 - Motivasi",
    coverColor: "from-red-650 to-rose-950",
    description: "Kerangka psikologi mengukir nasib, memulihkan kawalan emosi fizikal dan kestabilan tahap kewangan kendiri.",
    publishYear: 1991,
    pages: 410
  },
  {
    id: "PS-MT-0072",
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    category: "Motivasi",
    type: "Fizikal",
    status: "Tersedia",
    location: "Rak M1 - Motivasi",
    coverColor: "from-purple-750 to-orange-950",
    description: "Menggugat pemikiran konvensional celik kewangan, membincangkan perbezaan aset, liabiliti, dan pemetaan kebebasan sara hidup.",
    publishYear: 1995,
    pages: 250
  },

  // --- 8. Buletin (B) ---
  {
    id: "PS-B-0001",
    title: "Buletin Rancang PLANMalaysia@Pulau Pinang Edisi 1&2 - 2021",
    author: "PLANMalaysia@Pulau Pinang",
    category: "Buletin",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-indigo-650 to-sky-900",
    description: "Risalah menceritakan inisiatif reka bentuk bandar mampan dan tadbir urus Pulau Pinang fasa rendah karbon mampan.",
    publishYear: 2021,
    pages: 65
  },
  {
    id: "PS-B-0004",
    title: "Buletin PLANMalaysia@Perak Edisi 2022",
    author: "PLANMalaysia@Perak",
    category: "Buletin",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-orange-600 to-amber-900",
    description: "Kompilasi ringkas statistik spatial, pembendungan banjir di Kerian, Perak dan zon and syarat guna tanah industri.",
    publishYear: 2022,
    pages: 50
  },
  {
    id: "PS-B-0006",
    title: "The PLANMalaysia Magazine 2023",
    author: "PLANMalaysia",
    category: "Buletin",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-blue-700 to-indigo-950",
    description: "Penerbitan tahunan memaparkan inovasi pemetaan geografi perbandaran di Semenanjung Malaysia bernilai spatial.",
    publishYear: 2023,
    pages: 75
  },
  {
    id: "PS-B-0010",
    title: "Buletin Rancang PLANMalaysia@Kedah Edisi 2024",
    author: "PLANMalaysia@Kedah",
    category: "Buletin",
    type: "Digital",
    status: "Tersedia",
    location: "Awan Digital PPZU",
    coverColor: "from-indigo-700 to-teal-900",
    description: "Risalah reka bentuk perbandaran cergas, laporan pengurusan sisa bersepadu serta pemetaan spatial Kedah.",
    publishYear: 2024,
    pages: 58
  }
];
